// Local source entry for @analogjs/astro-angular. The integration transforms
// standalone Angular components from project TypeScript files; package entry
// aliases stay in the package and are re-exported here for MDX islands.
export {
  KrdsAccordionComponent as AngularAccordion,
  KrdsAccordionLineComponent as AngularAccordionLine,
  KrdsBadgeComponent as AngularBadge,
  KrdsBadgeNumberComponent as AngularBadgeNumber,
  KrdsBadgeSizeComponent as AngularBadgeSize,
  KrdsBreadcrumbComponent as AngularBreadcrumb,
  KrdsButtonComponent as AngularButton,
  KrdsButtonHierarchyComponent as AngularButtonHierarchy,
  KrdsButtonIconComponent as AngularButtonIcon,
  KrdsButtonSizeComponent as AngularButtonSize,
  KrdsButtonTextComponent as AngularButtonText,
  KrdsButtonWithIconComponent as AngularButtonWithIcon,
  KrdsCalendarComponent as AngularCalendar,
  KrdsCalendarRangeComponent as AngularCalendarRange,
  KrdsCarouselComponent as AngularCarousel,
  KrdsCarouselBannerComponent as AngularCarouselBanner,
  KrdsCheckboxComponent as AngularCheckbox,
  KrdsCheckboxChipComponent as AngularCheckboxChip,
  KrdsCheckboxSizeComponent as AngularCheckboxSize,
  KrdsCoachMarkComponent as AngularCoachMark,
  KrdsContextualHelpComponent as AngularContextualHelp,
  KrdsCriticalAlertsComponent as AngularCriticalAlerts,
  KrdsDateInputComponent as AngularDateInput,
  KrdsDisclosureComponent as AngularDisclosure,
  KrdsFaviconComponent as AngularFavicon,
  KrdsFileUploadComponent as AngularFileUpload,
  KrdsFooterComponent as AngularFooter,
  KrdsHeaderComponent as AngularHeader,
  KrdsHelpPanelComponent as AngularHelpPanel,
  KrdsIdentifierComponent as AngularIdentifier,
  KrdsInPageNavigationComponent as AngularInPageNavigation,
  KrdsLanguageSwitcherComponent as AngularLanguageSwitcher,
  KrdsLanguageSwitcherPageComponent as AngularLanguageSwitcherPage,
  KrdsLinkComponent as AngularLink,
  KrdsMainMenuMobileComponent as AngularMainMenuMobile,
  KrdsMainMenuPcComponent as AngularMainMenuPc,
  KrdsMastheadComponent as AngularMasthead,
  KrdsModalComponent as AngularModal,
  KrdsModalSampleComponent as AngularModalSample,
  KrdsPaginationComponent as AngularPagination,
  KrdsRadioComponent as AngularRadio,
  KrdsRadioButtonComponent as AngularRadioButton,
  KrdsRadioChipComponent as AngularRadioChip,
  KrdsRadioSizeComponent as AngularRadioSize,
  KrdsResizeComponent as AngularResize,
  KrdsSelectComponent as AngularSelect,
  KrdsSelectSizeComponent as AngularSelectSize,
  KrdsSelectSortingComponent as AngularSelectSorting,
  KrdsSelectStateComponent as AngularSelectState,
  KrdsSideNavigationComponent as AngularSideNavigation,
  KrdsSkipLinkComponent as AngularSkipLink,
  KrdsSpinnerComponent as AngularSpinner,
  KrdsStepIndicatorComponent as AngularStepIndicator,
  KrdsStructuredListComponent as AngularStructuredList,
  KrdsStructuredListTableComponent as AngularStructuredListTable,
  KrdsSwitchComponent as AngularSwitch,
  KrdsTabComponent as AngularTab,
  KrdsTableComponent as AngularTable,
  KrdsTagComponent as AngularTag,
  KrdsTagLinkComponent as AngularTagLink,
  KrdsTextareaComponent as AngularTextarea,
  KrdsTextInputIconComponent as AngularTextInputIcon,
  KrdsTextInputSizeComponent as AngularTextInputSize,
  KrdsTextInputStateComponent as AngularTextInputState,
  KrdsTextInputComponent as AngularTextInput,
  KrdsTextListComponent as AngularTextList,
  KrdsTextListOrderedComponent as AngularTextListOrdered,
  KrdsToggleSwitchComponent as AngularToggleSwitch,
  KrdsToggleSwitchSizeComponent as AngularToggleSwitchSize,
  KrdsTooltipComponent as AngularTooltip,
  KrdsTooltipBoxComponent as AngularTooltipBox,
  KrdsTooltipVerticalComponent as AngularTooltipVertical,
  KrdsTtsComponent as AngularTts,
  KrdsTtsIconComponent as AngularTtsIcon,
  KrdsTtsSizeComponent as AngularTtsSize,
  KrdsTutorialPanelComponent as AngularTutorialPanel,
} from "../../../../packages/angular/src/index.ts";

export { KrdsSearchSuggestionsComponent as AngularSearchSuggestions } from "../../../../packages/angular/src/extra.ts";
export type { KrdsSearchSuggestion as AngularSearchSuggestion } from "../../../../packages/angular/src/extra.ts";
export { KrdsValidatedInputComponent as AngularValidatedInput } from "../../../../packages/angular/src/extra.ts";
export { KrdsFilterableListComponent as AngularFilterableList } from "../../../../packages/angular/src/extra.ts";
