import { spawn } from "node:child_process";
import { mkdir, mkdtemp, readFile, rename, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isDeepStrictEqual } from "node:util";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const runtimePath = resolve(repositoryRoot, "scripts/conformance/runtime.mjs");
const frameworkIds = ["react", "vue", "svelte", "solid", "angular", "astro"];
const requiredChecks = ["render", "dom", "accessibility", "behavior", "form", "visual", "contract"];
const arguments_ = process.argv.slice(2);
let outputArgument;
let saveDiffs = false;
let catalogArgument;

for (let index = 0; index < arguments_.length; index += 1) {
  const argument = arguments_[index];
  if (argument === "--save-diffs") {
    saveDiffs = true;
    continue;
  }
  if (argument === "--catalog") {
    const value = arguments_[index + 1];
    if (!value || value.startsWith("--")) throw new Error("--catalog requires a file path");
    catalogArgument = value;
    index += 1;
    continue;
  }
  if (argument === "--output") {
    const value = arguments_[index + 1];
    if (!value || value.startsWith("--")) throw new Error("--output requires a file path");
    outputArgument = value;
    index += 1;
    continue;
  }
  throw new Error(
    `Unsupported strict runtime option: ${argument}. Full evidence always executes every fixture, framework, check, and visual comparison.`,
  );
}

const outputPath = resolve(repositoryRoot, outputArgument ?? "reports/conformance-runtime.json");
const temporaryOutputPath = `${outputPath}.${process.pid}.tmp`;
const runStartedAt = Date.now();
await Promise.all([rm(outputPath, { force: true }), rm(temporaryOutputPath, { force: true })]);

const catalog = JSON.parse(
  await readFile(
    resolve(repositoryRoot, catalogArgument ?? "apps/conformance-host/dist/fixtures.json"),
    "utf8",
  ),
);
if (!catalog.upstream || !Array.isArray(catalog.fixtures)) {
  throw new Error("The current conformance host build did not produce a valid fixture catalog");
}
// 카탈로그 기반으로 기대값을 계산한다 (공식/extra 스위트 모두 동작).
const requiredFixtureCount = catalog.fixtures.length;

const fixtureById = new Map();
const expectedStateKeys = new Set();
for (const fixture of catalog.fixtures) {
  if (!fixture?.id || fixtureById.has(fixture.id)) {
    throw new Error(
      `Fixture catalog contains a missing or duplicate id: ${fixture?.id ?? "<missing>"}`,
    );
  }
  if (!fixture.componentId || !Array.isArray(fixture.states) || fixture.states.length === 0) {
    throw new Error(`${fixture.id}: executable component/state contract is incomplete`);
  }
  fixtureById.set(fixture.id, fixture);
  const stateIds = new Set();
  for (const state of fixture.states) {
    if (!state?.id || stateIds.has(state.id)) {
      throw new Error(
        `${fixture.id}: state id is missing or duplicated: ${state?.id ?? "<missing>"}`,
      );
    }
    stateIds.add(state.id);
    expectedStateKeys.add(`${fixture.id}\0${state.id}`);
  }
}
const expectedFixtureIds = [...fixtureById.keys()].sort();
const temporaryDirectory = await mkdtemp(resolve(tmpdir(), "krds-conformance-"));

const assertFreshTimestamp = (value, framework) => {
  const timestamp = Date.parse(value);
  if (
    !Number.isFinite(timestamp) ||
    timestamp < runStartedAt - 1_000 ||
    timestamp > Date.now() + 1_000
  ) {
    throw new Error(`${framework}: worker evidence was not generated by the current run`);
  }
};

const validateWorkerReport = (report, framework, exitCode) => {
  if (!report || report.schemaVersion !== 1) {
    throw new Error(`${framework}: invalid runtime evidence schema`);
  }
  assertFreshTimestamp(report.generatedAt, framework);
  if (!isDeepStrictEqual(report.upstream, catalog.upstream)) {
    throw new Error(`${framework}: runtime evidence does not match the current upstream catalog`);
  }
  if (
    !report.browser ||
    report.browser.name !== "chromium" ||
    typeof report.browser.version !== "string"
  ) {
    throw new Error(`${framework}: Chromium runtime identity is missing`);
  }
  if (!isDeepStrictEqual(report.frameworks, [framework])) {
    throw new Error(`${framework}: worker evidence contains a different framework selection`);
  }
  if (
    report.fixtureCount !== requiredFixtureCount ||
    report.stateCount !== expectedStateKeys.size ||
    !Array.isArray(report.results)
  ) {
    throw new Error(`${framework}: worker evidence does not cover the exact fixture/state catalog`);
  }

  const actualStateKeys = new Set();
  const fixturePassing = new Map(expectedFixtureIds.map((fixtureId) => [fixtureId, true]));
  for (const result of report.results) {
    const fixture = fixtureById.get(result?.fixtureId);
    const stateKey = `${result?.fixtureId}\0${result?.state}`;
    if (
      result?.framework !== framework ||
      !fixture ||
      result.componentId !== fixture.componentId ||
      !expectedStateKeys.has(stateKey) ||
      actualStateKeys.has(stateKey)
    ) {
      throw new Error(`${framework}: unexpected or duplicate executable state ${stateKey}`);
    }
    actualStateKeys.add(stateKey);
    const checksPass = requiredChecks.every(
      (check) => typeof result.checks?.[check]?.passed === "boolean" && result.checks[check].passed,
    );
    if (!requiredChecks.every((check) => typeof result.checks?.[check]?.passed === "boolean")) {
      throw new Error(`${framework}/${result.fixtureId}/${result.state}: check result is missing`);
    }
    const expectedStatus = checksPass ? "passing" : "failing";
    if (result.status !== expectedStatus) {
      throw new Error(
        `${framework}/${result.fixtureId}/${result.state}: status disagrees with executable checks`,
      );
    }
    if (!checksPass) fixturePassing.set(result.fixtureId, false);
  }
  if (
    actualStateKeys.size !== expectedStateKeys.size ||
    [...expectedStateKeys].some((key) => !actualStateKeys.has(key))
  ) {
    throw new Error(`${framework}: one or more executable fixture states are missing`);
  }

  if (!Array.isArray(report.evidence) || report.evidence.length !== 1) {
    throw new Error(`${framework}: expected exactly one framework evidence record`);
  }
  const evidence = report.evidence[0];
  if (
    evidence?.framework !== framework ||
    evidence.source !== "scripts/conformance/runtime.mjs" ||
    !Array.isArray(evidence.fixtureResults) ||
    evidence.fixtureResults.length !== requiredFixtureCount ||
    !Array.isArray(evidence.unresolvedSelectors) ||
    !Array.isArray(evidence.errata) ||
    !Array.isArray(evidence.errors)
  ) {
    throw new Error(`${framework}: malformed framework evidence`);
  }
  const evidenceByFixture = new Map();
  for (const result of evidence.fixtureResults) {
    if (!fixtureById.has(result?.fixtureId) || evidenceByFixture.has(result.fixtureId)) {
      throw new Error(
        `${framework}: unexpected or duplicate fixture evidence ${result?.fixtureId}`,
      );
    }
    const expectedStatus = fixturePassing.get(result.fixtureId) ? "passing" : "failing";
    if (result.status !== expectedStatus) {
      throw new Error(`${framework}/${result.fixtureId}: evidence disagrees with runtime states`);
    }
    evidenceByFixture.set(result.fixtureId, result);
  }
  if (expectedFixtureIds.some((fixtureId) => !evidenceByFixture.has(fixtureId))) {
    throw new Error(`${framework}: fixture evidence is incomplete`);
  }

  const workerPasses =
    [...fixturePassing.values()].every(Boolean) &&
    evidence.status === "passing" &&
    evidence.unresolvedSelectors.length === 0 &&
    evidence.errors.length === 0;
  if (report.strictConformance !== workerPasses) {
    throw new Error(`${framework}: strict status disagrees with executable evidence`);
  }
  if (exitCode !== (workerPasses ? 0 : 1)) {
    throw new Error(
      `${framework}: worker exit code ${exitCode} did not propagate strict status ${workerPasses}`,
    );
  }
};

const runFramework = async (framework) => {
  const startedAt = performance.now();
  const shardPath = resolve(temporaryDirectory, `${framework}.json`);
  console.log(`[${framework}] started`);
  const runtimeArguments = [
    runtimePath,
    "--framework",
    framework,
    "--output",
    shardPath,
    ...(catalogArgument
      ? ["--catalog", resolve(repositoryRoot, catalogArgument)]
      : []),
    ...(saveDiffs
      ? ["--save-diffs", "--diff-directory", resolve(dirname(outputPath), "conformance-diffs")]
      : []),
  ];
  let stderr = "";
  const exitCode = await new Promise((resolvePromise, reject) => {
    const child = spawn(process.execPath, runtimeArguments, {
      cwd: repositoryRoot,
      stdio: ["ignore", "pipe", "pipe"],
    });
    child.stdout.resume();
    child.stderr.setEncoding("utf8");
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("close", (code, signal) => {
      if (signal) {
        reject(new Error(`[${framework}] worker received ${signal}\n${stderr.trim()}`));
        return;
      }
      if (code !== 0 && code !== 1) {
        reject(new Error(`[${framework}] worker exited with code ${code}\n${stderr.trim()}`));
        return;
      }
      resolvePromise(code);
    });
  });

  let report;
  try {
    report = JSON.parse(await readFile(shardPath, "utf8"));
  } catch (error) {
    throw new Error(
      `[${framework}] worker did not produce readable current-run evidence: ${
        error instanceof Error ? error.message : String(error)
      }\n${stderr.trim()}`,
    );
  }
  validateWorkerReport(report, framework, exitCode);
  const elapsedSeconds = ((performance.now() - startedAt) / 1_000).toFixed(1);
  const passingStates = report.results.filter((result) => result.status === "passing").length;
  console.log(
    `[${framework}] ${report.strictConformance ? "passed" : "failed"} ${passingStates}/${report.stateCount} states in ${elapsedSeconds}s`,
  );
  return report;
};

try {
  const reports = await Promise.all(frameworkIds.map(runFramework));
  if (
    reports.some(
      (report) =>
        report.browser.name !== reports[0].browser.name ||
        report.browser.version !== reports[0].browser.version,
    )
  ) {
    throw new Error("Framework workers did not execute with the same browser runtime");
  }

  const results = reports.flatMap((report) => report.results);
  const evidence = reports.flatMap((report) => report.evidence);
  const executedFixtures = new Set(
    results.map((result) => `${result.framework}\0${result.fixtureId}`),
  );
  const expectedEvidenceCount = requiredFixtureCount * frameworkIds.length;
  const failures = [
    ...results
      .filter((result) => result.status !== "passing")
      .map((result) => `${result.framework}/${result.fixtureId}/${result.state}`),
    ...evidence.flatMap((entry) => [
      ...entry.errors.map((error) => `${entry.framework}: ${error}`),
      ...entry.unresolvedSelectors.map(
        (selector) => `${entry.framework}: unresolved selector ${selector}`,
      ),
    ]),
  ];
  const uniqueFailures = [...new Set(failures)].sort();
  const strictConformance =
    evidence.length === frameworkIds.length &&
    evidence.reduce((sum, entry) => sum + entry.fixtureResults.length, 0) ===
      expectedEvidenceCount &&
    executedFixtures.size === expectedEvidenceCount &&
    results.every((result) => result.status === "passing") &&
    evidence.every(
      (entry) =>
        entry.status === "passing" &&
        entry.fixtureResults.every((result) => result.status === "passing") &&
        entry.unresolvedSelectors.length === 0 &&
        entry.errors.length === 0,
    ) &&
    uniqueFailures.length === 0;
  const unresolvedSelectors = [...new Set(evidence.flatMap((entry) => entry.unresolvedSelectors))];
  const errata = [...new Set(evidence.flatMap((entry) => entry.errata))];
  const report = {
    schemaVersion: 1,
    reportType: "runtime-strict-evidence",
    runStartedAt: new Date(runStartedAt).toISOString(),
    generatedAt: new Date().toISOString(),
    upstream: catalog.upstream,
    browser: reports[0].browser,
    frameworkIds,
    frameworks: evidence,
    fixtureCount: expectedEvidenceCount,
    evidenceCount: expectedEvidenceCount,
    executableFixtureCount: requiredFixtureCount,
    executedFixtureCount: executedFixtures.size,
    stateCount: results.length,
    unresolvedCount: unresolvedSelectors.length,
    errataCount: errata.length,
    failures: uniqueFailures,
    results,
    evidence,
    strictConformance,
  };

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(temporaryOutputPath, `${JSON.stringify(report, null, 2)}\n`);
  await rename(temporaryOutputPath, outputPath);
  const passingStates = results.filter((result) => result.status === "passing").length;
  console.log(
    `Runtime conformance ${strictConformance ? "passed" : "failed"}: ${passingStates}/${results.length} states and ${executedFixtures.size}/${expectedEvidenceCount} executable framework fixtures.`,
  );
  if (!strictConformance) process.exitCode = 1;
} finally {
  await Promise.all([
    rm(temporaryDirectory, { recursive: true, force: true }),
    rm(temporaryOutputPath, { force: true }),
  ]);
}
