import type { Component, ComponentProps } from 'svelte';
import type Additional from './Additional.svelte';
import type Accordion from './Accordion.svelte';

type AdditionalPreset = Component<Omit<ComponentProps<typeof Additional>, 'kind'>>;

export { default as Accordion } from './Accordion.svelte';
export declare const AccordionLine: typeof Accordion;
export { default as Button } from './Button.svelte';
export { default as Checkbox } from './Checkbox.svelte';
export { default as Radio } from './Radio.svelte';
export { default as Switch } from './Switch.svelte';
export { default as TextInput } from './TextInput.svelte';
export { default as TextInputSize } from './TextInput.svelte';
export { default as TextInputState } from './TextInput.svelte';
export declare const Badge: AdditionalPreset;
export declare const BadgeNumber: AdditionalPreset;
export declare const BadgeSize: AdditionalPreset;
export declare const Breadcrumb: AdditionalPreset;
export declare const ButtonHierarchy: AdditionalPreset;
export declare const ButtonIcon: AdditionalPreset;
export declare const ButtonSize: AdditionalPreset;
export declare const ButtonText: AdditionalPreset;
export declare const ButtonWithIcon: AdditionalPreset;
export declare const Calendar: AdditionalPreset;
export declare const CalendarRange: AdditionalPreset;
export declare const Carousel: AdditionalPreset;
export declare const CarouselBanner: AdditionalPreset;
export declare const CheckboxChip: AdditionalPreset;
export declare const CheckboxSize: AdditionalPreset;
export declare const CoachMark: AdditionalPreset;
export declare const ContextualHelp: AdditionalPreset;
export declare const CriticalAlerts: AdditionalPreset;
export declare const DateInput: AdditionalPreset;
export declare const Disclosure: AdditionalPreset;
export declare const Favicon: AdditionalPreset;
export declare const FileUpload: AdditionalPreset;
export declare const Footer: AdditionalPreset;
export declare const Header: AdditionalPreset;
export declare const HelpPanel: AdditionalPreset;
export declare const Identifier: AdditionalPreset;
export declare const InPageNavigation: AdditionalPreset;
export declare const LanguageSwitcher: AdditionalPreset;
export declare const LanguageSwitcherPage: AdditionalPreset;
export declare const Link: AdditionalPreset;
export declare const MainMenuMobile: AdditionalPreset;
export declare const MainMenuPc: AdditionalPreset;
export declare const Masthead: AdditionalPreset;
export declare const Modal: AdditionalPreset;
export declare const ModalSample: AdditionalPreset;
export declare const Pagination: AdditionalPreset;
export declare const RadioButton: AdditionalPreset;
export declare const RadioChip: AdditionalPreset;
export declare const RadioSize: AdditionalPreset;
export declare const Resize: AdditionalPreset;
export declare const Select: AdditionalPreset;
export declare const SelectSize: AdditionalPreset;
export declare const SelectSorting: AdditionalPreset;
export declare const SelectState: AdditionalPreset;
export declare const SideNavigation: AdditionalPreset;
export declare const SkipLink: AdditionalPreset;
export declare const Spinner: AdditionalPreset;
export declare const StepIndicator: AdditionalPreset;
export declare const StructuredList: AdditionalPreset;
export declare const StructuredListTable: AdditionalPreset;
export declare const Tab: AdditionalPreset;
export declare const Table: AdditionalPreset;
export declare const Tag: AdditionalPreset;
export declare const TagLink: AdditionalPreset;
export declare const Textarea: AdditionalPreset;
export declare const TextInputIcon: AdditionalPreset;
export declare const TextList: AdditionalPreset;
export declare const TextListOrdered: AdditionalPreset;
export declare const ToggleSwitch: AdditionalPreset;
export declare const ToggleSwitchSize: AdditionalPreset;
export declare const Tooltip: AdditionalPreset;
export declare const TooltipBox: AdditionalPreset;
export declare const TooltipVertical: AdditionalPreset;
export declare const Tts: AdditionalPreset;
export declare const TtsIcon: AdditionalPreset;
export declare const TtsSize: AdditionalPreset;
export declare const TutorialPanel: AdditionalPreset;
