import type { Component, ComponentProps } from "svelte";
import type BadgeComponent from "./Badge.svelte";
import type CalendarComponent from "./Calendar.svelte";
import type CarouselComponent from "./Carousel.svelte";
import type LanguageSwitcherComponent from "./LanguageSwitcher.svelte";
import type TooltipComponent from "./Tooltip.svelte";
import type TtsComponent from "./Tts.svelte";
type BadgeProps = ComponentProps<BadgeComponent>;
type CalendarProps = ComponentProps<CalendarComponent>;
type CarouselProps = ComponentProps<CarouselComponent>;
type LanguageSwitcherProps = ComponentProps<LanguageSwitcherComponent>;
type TooltipProps = ComponentProps<TooltipComponent>;
type TtsProps = ComponentProps<TtsComponent>;
export { default as Accordion } from "./Accordion.svelte";
export declare const AccordionLine: typeof import("./Accordion.svelte").default;
export { default as Button } from "./Button.svelte";
export { default as Checkbox } from "./Checkbox.svelte";
export { default as Radio } from "./Radio.svelte";
export { default as Switch } from "./Switch.svelte";
export { default as TextInput } from "./TextInput.svelte";
export { default as TextInputSize } from "./TextInput.svelte";
export { default as TextInputState } from "./TextInput.svelte";
export { default as Badge } from "./Badge.svelte";
export declare const BadgeNumber: Component<Omit<BadgeProps, "number"> & { number?: boolean }>;
export declare const BadgeSize: Component<BadgeProps>;
export { default as Breadcrumb } from "./Breadcrumb.svelte";
export { default as ButtonHierarchy } from "./ButtonHierarchy.svelte";
export { default as ButtonIcon } from "./ButtonIcon.svelte";
export { default as ButtonSize } from "./ButtonSize.svelte";
export { default as ButtonText } from "./ButtonText.svelte";
export { default as ButtonWithIcon } from "./ButtonWithIcon.svelte";
export { default as Calendar } from "./Calendar.svelte";
export declare const CalendarRange: Component<Omit<CalendarProps, "kind"> & { kind?: string }>;
export declare const DateInput: typeof import("./Calendar.svelte").default;
export { default as Carousel } from "./Carousel.svelte";
export declare const CarouselBanner: Component<Omit<CarouselProps, "kind"> & { kind?: string }>;
export { default as CheckboxChip } from "./CheckboxChip.svelte";
export { default as CheckboxSize } from "./CheckboxSize.svelte";
export { default as CoachMark } from "./CoachMark.svelte";
export { default as ContextualHelp } from "./ContextualHelp.svelte";
export { default as CriticalAlerts } from "./CriticalAlerts.svelte";
export { default as Disclosure } from "./Disclosure.svelte";
export { default as Favicon } from "./Favicon.svelte";
export { default as FileUpload } from "./FileUpload.svelte";
export { default as Footer } from "./Footer.svelte";
export { default as Header } from "./Header.svelte";
export { default as HelpPanel } from "./HelpPanel.svelte";
export { default as Identifier } from "./Identifier.svelte";
export { default as InPageNavigation } from "./InPageNavigation.svelte";
export { default as LanguageSwitcher } from "./LanguageSwitcher.svelte";
export declare const LanguageSwitcherPage: Component<
  Omit<LanguageSwitcherProps, "kind"> & { kind?: string }
>;
export { default as Link } from "./Link.svelte";
export { default as MainMenuMobile } from "./MainMenuMobile.svelte";
export { default as MainMenuPc } from "./MainMenuPc.svelte";
export { default as Masthead } from "./Masthead.svelte";
export { default as Modal } from "./Modal.svelte";
export declare const ModalSample: typeof import("./Modal.svelte").default;
export { default as Pagination } from "./Pagination.svelte";
export { default as RadioButton } from "./RadioButton.svelte";
export { default as RadioChip } from "./RadioChip.svelte";
export { default as RadioSize } from "./RadioSize.svelte";
export { default as Resize } from "./Resize.svelte";
export { default as Select } from "./Select.svelte";
export declare const SelectSize: typeof import("./Select.svelte").default;
export declare const SelectState: typeof import("./Select.svelte").default;
export { default as SelectSorting } from "./SelectSorting.svelte";
export { default as SideNavigation } from "./SideNavigation.svelte";
export { default as SkipLink } from "./SkipLink.svelte";
export { default as Spinner } from "./Spinner.svelte";
export { default as StepIndicator } from "./StepIndicator.svelte";
export { default as StructuredList } from "./StructuredList.svelte";
export { default as StructuredListTable } from "./StructuredListTable.svelte";
export { default as Tab } from "./Tab.svelte";
export { default as Table } from "./Table.svelte";
export { default as Tag } from "./Tag.svelte";
export { default as TagLink } from "./TagLink.svelte";
export { default as Textarea } from "./Textarea.svelte";
export { default as TextInputIcon } from "./TextInputIcon.svelte";
export { default as TextList } from "./TextList.svelte";
export { default as TextListOrdered } from "./TextListOrdered.svelte";
export { default as ToggleSwitch } from "./ToggleSwitch.svelte";
export declare const ToggleSwitchSize: typeof import("./ToggleSwitch.svelte").default;
export { default as Tooltip } from "./Tooltip.svelte";
export declare const TooltipBox: Component<Omit<TooltipProps, "kind"> & { kind?: string }>;
export declare const TooltipVertical: Component<Omit<TooltipProps, "kind"> & { kind?: string }>;
export { default as Tts } from "./Tts.svelte";
export { default as TtsIcon } from "./TtsIcon.svelte";
export { default as TtsSize } from "./TtsSize.svelte";
export { default as TutorialPanel } from "./TutorialPanel.svelte";
