import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { cp, mkdir, readFile, readdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const upstreamRoot = join(root, 'upstream');
const snapshotRoot = join(upstreamRoot, 'krds-html');
const lockPath = join(upstreamRoot, 'upstream.lock.json');
const manifestPath = join(upstreamRoot, 'snapshot-manifest.json');
const lock = JSON.parse(await readFile(lockPath, 'utf8'));

const walk = async (directory) => {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (entry.name === '.git') continue;
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(path)));
    else files.push(path);
  }
  return files;
};

const digestFile = async (path) => {
  const content = await readFile(path);
  return createHash('sha512').update(content).digest('hex');
};

const snapshotFiles = async () => {
  const files = await walk(snapshotRoot);
  const result = {};
  for (const path of files.sort()) result[relative(snapshotRoot, path)] = await digestFile(path);
  return result;
};

const remoteCommit = () =>
  execFileSync('git', ['ls-remote', `https://github.com/${lock.repository}.git`, lock.ref], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
  })
    .trim()
    .split(/\s+/)[0];

const writeSnapshotMetadata = async () => {
  await writeFile(
    join(snapshotRoot, 'SOURCE.md'),
    `# KRDS HTML Component Kit source\n\nRepository: https://github.com/${lock.repository}\n\n- Ref: ${lock.ref}\n- Commit: ${lock.commit}\n- Package: krds-uiux@${lock.packageVersion}\n- Retrieved: ${lock.retrievedAt}\n- License: ${lock.license}\n\n출처: KRDS (KoRea Design System)\n본 저작물은 행정안전부에서 공공누리 제1유형으로 개방한 KRDS 디자인시스템을 이용하였습니다.\n\nThis snapshot is generated by pnpm upstream:sync. Do not edit it manually.\n`,
  );
  await writeFile(
    join(snapshotRoot, 'LICENSE'),
    `KRDS HTML Component Kit source materials remain subject to upstream terms and KOGL Type 1 attribution requirements.\n\n출처: KRDS (KoRea Design System)\n본 저작물은 행정안전부에서 공공누리 제1유형으로 개방한 KRDS 디자인시스템을 이용하였습니다.\n\nSource: https://github.com/${lock.repository}\n`,
  );
};
const snapshotMatchesLock = async () => {
  try {
    return (await readFile(join(snapshotRoot, 'SOURCE.md'), 'utf8')).includes(
      `Commit: ${lock.commit}`,
    );
  } catch {
    return false;
  }
};

const sync = async () => {
  const current = remoteCommit();
  if (current !== lock.commit) {
    throw new Error(`Lock ref ${lock.ref} resolves to ${current}, not ${lock.commit}`);
  }

  let exists = false;
  try {
    await stat(join(snapshotRoot, 'package.json'));
    exists = true;
  } catch {
    // Snapshot is absent and will be cloned below.
  }

  const needsClone = !exists || !(await snapshotMatchesLock());
  if (needsClone) {
    if (exists) {
      try {
        const recorded = JSON.parse(await readFile(manifestPath, 'utf8'));
        const currentFiles = await snapshotFiles();
        const dirty =
          Object.keys(currentFiles).some((path) => currentFiles[path] !== recorded.files[path]) ||
          Object.keys(recorded.files).some((path) => currentFiles[path] !== recorded.files[path]);
        if (dirty) throw new Error('Refusing to replace a modified upstream snapshot.');
      } catch (error) {
        if (error instanceof SyntaxError)
          throw new Error('Cannot replace snapshot without a valid snapshot manifest.');
        throw error;
      }
    }
    const temporary = join(upstreamRoot, `.krds-html-${lock.commit}`);
    await rm(temporary, { recursive: true, force: true });
    execFileSync(
      'git',
      [
        'clone',
        '--depth',
        '1',
        '--branch',
        lock.ref,
        `https://github.com/${lock.repository}.git`,
        temporary,
      ],
      { cwd: root, stdio: 'inherit' },
    );
    await rm(join(temporary, '.git'), { recursive: true, force: true });
    if (exists) await rm(snapshotRoot, { recursive: true, force: true });
    await rename(temporary, snapshotRoot);
  }

  await writeSnapshotMetadata();
  await writeFile(
    manifestPath,
    `${JSON.stringify({ commit: lock.commit, files: await snapshotFiles() }, null, 2)}\n`,
  );
  console.log(`Upstream ${lock.repository}@${lock.ref} is synced at ${lock.commit}.`);
};

const check = async () => {
  const current = remoteCommit();
  const files = await snapshotFiles();
  let recorded = null;
  try {
    recorded = JSON.parse(await readFile(manifestPath, 'utf8'));
  } catch {
    // A missing manifest is a bootstrap condition.
  }
  const changed = recorded
    ? Object.keys(files).some((path) => files[path] !== recorded.files[path]) ||
      Object.keys(recorded.files).some((path) => files[path] !== recorded.files[path])
    : false;
  if (current !== lock.commit) {
    console.log(`New upstream revision available: ${current} (locked: ${lock.commit}).`);
    process.exitCode = 1;
  }
  if (changed) {
    console.error('Snapshot files differ from the recorded immutable manifest.');
    process.exitCode = 1;
  }
  if (current === lock.commit && !changed) console.log(`Upstream lock is current: ${lock.commit}.`);
};

const diff = async () => {
  const current = await snapshotFiles();
  let recorded = { files: {} };
  try {
    recorded = JSON.parse(await readFile(manifestPath, 'utf8'));
  } catch {
    // The first diff reports every snapshot file as added.
  }
  const paths = [...new Set([...Object.keys(recorded.files), ...Object.keys(current)])].sort();
  const entries = paths.map((path) => ({
    path,
    status: !recorded.files[path]
      ? 'added'
      : !current[path]
        ? 'removed'
        : recorded.files[path] === current[path]
          ? 'unchanged'
          : 'changed',
  }));
  const report = { upstream: lock, generatedAt: new Date().toISOString(), entries };
  await mkdir(join(root, 'reports'), { recursive: true });
  await writeFile(join(root, 'reports/upstream-diff.json'), `${JSON.stringify(report, null, 2)}\n`);
  await writeFile(
    join(root, 'reports/upstream-diff.md'),
    `# Upstream diff\n\n- Repository: ${lock.repository}\n- Ref: ${lock.ref}\n- Commit: ${lock.commit}\n\n| Path | Status |\n| --- | --- |\n${entries.map((entry) => `| ${entry.path} | ${entry.status} |`).join('\n')}\n`,
  );
  console.log(
    `Wrote reports/upstream-diff.{json,md} (${entries.filter((entry) => entry.status !== 'unchanged').length} changes).`,
  );
};

const extract = async () => {
  const files = (await walk(join(snapshotRoot, 'html/code'))).filter((path) =>
    path.endsWith('.html'),
  );
  const inventory = files.sort().map((path) => ({
    id: relative(join(snapshotRoot, 'html/code'), path)
      .replace(/\.html$/, '')
      .replaceAll('_', '-'),
    source: relative(root, path),
    fixtureCount: 1,
    status: 'unmapped',
  }));
  await mkdir(join(root, 'conformance/generated'), { recursive: true });
  const manifestDir = join(root, 'conformance/manifests');
  await mkdir(manifestDir, { recursive: true });
  for (const component of inventory) {
    const manifestPath = join(manifestDir, `${component.id}.yaml`);
    try {
      await stat(manifestPath);
    } catch {
      await writeFile(
        manifestPath,
        `id: ${component.id}\nstatus: unmapped\nupstream:\n  version: ${lock.packageVersion}\n  files:\n    - ${component.source}\nfixtures: []\ncontract:\n  semanticElement: unresolved\n  accessibility: []\n`,
      );
    }
  }
  await writeFile(
    join(root, 'conformance/generated/source-inventory.json'),
    `${JSON.stringify({ generatedFrom: lock, components: inventory }, null, 2)}\n`,
  );
  console.log(`Extracted ${inventory.length} upstream HTML component entries.`);
};

const command = process.argv[2] ?? 'check';
if (command === 'sync') await sync();
else if (command === 'check') await check();
else if (command === 'diff') await diff();
else if (command === 'extract') await extract();
else throw new Error(`Unknown upstream command: ${command}`);
